regions:
  example_region:
    pos1:
      x: 100
      y: 64
      z: 200
    pos2:
      x: 150
      y: 80
      z: 250
    command: "say &aGracz &e%player% &awszedł do regionu!"
    cooldown: 600